#### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

#### Reading CSV File

In [2]:
df=pd.read_csv(r'G:\My Drive\oil_spill.csv')
df

f_1    f_2      f_3     f_4  f_5       f_6    f_7    f_8      f_9  f_10   
0      1   2558  1506.09  456.63   90   6395000  40.88   7.89  29780.0  0.19  \
1      2  22325    79.11  841.03  180  55812500  51.11   1.21  61900.0  0.02   
2      3    115  1449.85  608.43   88    287500  40.42   7.34   3340.0  0.18   
3      4   1201  1562.53  295.65   66   3002500  42.40   7.97  18030.0  0.19   
4      5    312   950.27  440.86   37    780000  41.43   7.03   3350.0  0.17   
..   ...    ...      ...     ...  ...       ...    ...    ...      ...   ...   
932  200     12    92.42  364.42  135     97200  59.42  10.34    884.0  0.17   
933  201     11    98.82  248.64  159     89100  59.64  10.18    831.0  0.17   
934  202     14    25.14  428.86   24    113400  60.14  17.94    847.0  0.30   
935  203     10    96.00  451.30   68     81000  59.90  15.01    831.0  0.25   
936  204     11     7.73  235.73  135     89100  61.82  12.24    831.0  0.20   

     ...     f_41      f_42     f_43     f_44   f_45  f_46      f_47   f_48   
0    ...  2850.00   1000.00   763.16   135.46   3.73     0  33243.19  65.74  \
1    ...  5750.00  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73   
2    ...  1400.00    250.00   150.00    45.13   9.33     1  31692.84  65.81   
3    ...  6041.52    761.58   453.21   144.97  13.33     1  37696.21  65.67   
4    ...  1320.04    710.63   512.54   109.16   2.58     0  29038.17  65.66   
..   ...      ...       ...      ...      ...    ...   ...       ...    ...   
932  ...   381.84    254.56    84.85   146.97   4.50     0   2593.50  65.85   
933  ...   284.60    180.00   150.00    51.96   1.90     0   4361.25  65.70   
934  ...   402.49    180.00   180.00     0.00   2.24     0   2153.05  65.91   
935  ...   402.49    180.00    90.00    73.48   4.47     0   2421.43  65.97   
936  ...   254.56    254.56   127.28   180.00   2.00     0   3782.68  65.65   

     f_49  target  
0    7.95       1  
1    6.26       0  
2    7.84       1  
3    8.07       1  
4    7.35       0  
..    ...     ...  
932  6.39       0  
933  6.53       0  
934  6.12       0  
935  6.32       0  
936  6.26       0  

[937 rows x 50 columns]

In [3]:
df.shape

(937, 50)

In [4]:
df.describe()

f_1           f_2          f_3          f_4         f_5   
count  937.000000    937.000000   937.000000   937.000000  937.000000  \
mean    81.588047    332.842049   698.707086   870.992209   84.121665   
std     64.976730   1931.938570   599.965577   522.799325   45.361771   
min      1.000000     10.000000     1.920000     1.000000    0.000000   
25%     31.000000     20.000000    85.270000   444.200000   54.000000   
50%     64.000000     65.000000   704.370000   761.280000   73.000000   
75%    124.000000    132.000000  1223.480000  1260.370000  117.000000   
max    352.000000  32389.000000  1893.080000  2724.570000  180.000000   

                f_6         f_7         f_8            f_9        f_10  ...   
count  9.370000e+02  937.000000  937.000000     937.000000  937.000000  ...  \
mean   7.696964e+05   43.242721    9.127887    3940.712914    0.221003  ...   
std    3.831151e+06   12.718404    3.588878    8167.427625    0.090316  ...   
min    7.031200e+04   21.240000    0.830000     667.000000    0.020000  ...   
25%    1.250000e+05   33.650000    6.750000    1371.000000    0.160000  ...   
50%    1.863000e+05   39.970000    8.200000    2090.000000    0.200000  ...   
75%    3.304680e+05   52.420000   10.760000    3435.000000    0.260000  ...   
max    7.131500e+07   82.640000   24.690000  160740.000000    0.740000  ...   

               f_41          f_42         f_43         f_44        f_45   
count    937.000000    937.000000   937.000000   937.000000  937.000000  \
mean     933.928677    427.565582   255.435902   106.112519    5.014002   
std     1001.681331    715.391648   534.306194   135.617708    5.029151   
min        0.000000      0.000000     0.000000     0.000000    0.000000   
25%      450.000000    180.000000    90.800000    50.120000    2.370000   
50%      685.420000    270.000000   161.650000    73.850000    3.850000   
75%     1053.420000    460.980000   265.510000   125.810000    6.320000   
max    11949.330000  11500.000000  9593.480000  1748.130000   76.630000   

             f_46          f_47        f_48        f_49      target  
count  937.000000    937.000000  937.000000  937.000000  937.000000  
mean     0.128068   7985.718004   61.694386    8.119723    0.043757  
std      0.334344   6854.504915   10.412807    2.908895    0.204662  
min      0.000000   2051.500000   35.950000    5.810000    0.000000  
25%      0.000000   3760.570000   65.720000    6.340000    0.000000  
50%      0.000000   5509.430000   65.930000    7.220000    0.000000  
75%      0.000000   9521.930000   66.130000    7.840000    0.000000  
max      1.000000  55128.460000   66.450000   15.440000    1.000000  

[8 rows x 50 columns]

#### Handling Null Values

In [5]:
nv=df.isnull().sum()
nv=nv[nv>0]
nv

Series([], dtype: int64)

In [6]:
df.duplicated().sum()

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 937 entries, 0 to 936
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   f_1     937 non-null    int64  
 1   f_2     937 non-null    int64  
 2   f_3     937 non-null    float64
 3   f_4     937 non-null    float64
 4   f_5     937 non-null    int64  
 5   f_6     937 non-null    int64  
 6   f_7     937 non-null    float64
 7   f_8     937 non-null    float64
 8   f_9     937 non-null    float64
 9   f_10    937 non-null    float64
 10  f_11    937 non-null    float64
 11  f_12    937 non-null    float64
 12  f_13    937 non-null    float64
 13  f_14    937 non-null    float64
 14  f_15    937 non-null    float64
 15  f_16    937 non-null    float64
 16  f_17    937 non-null    float64
 17  f_18    937 non-null    float64
 18  f_19    937 non-null    float64
 19  f_20    937 non-null    float64
 20  f_21    937 non-null    float64
 21  f_22    937 non-null    float64
 22  f_

#### Correlation Matrix

In [8]:
correlation_matrix=df.corr()

#### Exploratory Data Analysis 


In [9]:
df['f_1'].value_counts()

f_1
3      9
5      9
6      9
8      9
9      9
      ..
261    1
266    1
267    1
269    1
204    1
Name: count, Length: 238, dtype: int64

In [10]:
df['f_23'].value_counts()

f_23
0    937
Name: count, dtype: int64

#### Dropping Highly Correlated Columns and making a Test Dataset

In [11]:
columns_to_drop = ['f_1','f_23']
test=df.drop(columns=columns_to_drop)
test

f_2      f_3     f_4  f_5       f_6    f_7    f_8      f_9  f_10   
0     2558  1506.09  456.63   90   6395000  40.88   7.89  29780.0  0.19  \
1    22325    79.11  841.03  180  55812500  51.11   1.21  61900.0  0.02   
2      115  1449.85  608.43   88    287500  40.42   7.34   3340.0  0.18   
3     1201  1562.53  295.65   66   3002500  42.40   7.97  18030.0  0.19   
4      312   950.27  440.86   37    780000  41.43   7.03   3350.0  0.17   
..     ...      ...     ...  ...       ...    ...    ...      ...   ...   
932     12    92.42  364.42  135     97200  59.42  10.34    884.0  0.17   
933     11    98.82  248.64  159     89100  59.64  10.18    831.0  0.17   
934     14    25.14  428.86   24    113400  60.14  17.94    847.0  0.30   
935     10    96.00  451.30   68     81000  59.90  15.01    831.0  0.25   
936     11     7.73  235.73  135     89100  61.82  12.24    831.0  0.20   

      f_11  ...     f_41      f_42     f_43     f_44   f_45  f_46      f_47   
0    214.7  ...  2850.00   1000.00   763.16   135.46   3.73     0  33243.19  \
1    901.7  ...  5750.00  11500.00  9593.48  1648.80   0.60     0  51572.04   
2     86.1  ...  1400.00    250.00   150.00    45.13   9.33     1  31692.84   
3    166.5  ...  6041.52    761.58   453.21   144.97  13.33     1  37696.21   
4    232.8  ...  1320.04    710.63   512.54   109.16   2.58     0  29038.17   
..     ...  ...      ...       ...      ...      ...    ...   ...       ...   
932  110.0  ...   381.84    254.56    84.85   146.97   4.50     0   2593.50   
933  107.2  ...   284.60    180.00   150.00    51.96   1.90     0   4361.25   
934  133.9  ...   402.49    180.00   180.00     0.00   2.24     0   2153.05   
935   97.5  ...   402.49    180.00    90.00    73.48   4.47     0   2421.43   
936  107.2  ...   254.56    254.56   127.28   180.00   2.00     0   3782.68   

      f_48  f_49  target  
0    65.74  7.95       1  
1    65.73  6.26       0  
2    65.81  7.84       1  
3    65.67  8.07       1  
4    65.66  7.35       0  
..     ...   ...     ...  
932  65.85  6.39       0  
933  65.70  6.53       0  
934  65.91  6.12       0  
935  65.97  6.32       0  
936  65.65  6.26       0  

[937 rows x 48 columns]

#### Test dataset shape

In [12]:
test.shape

(937, 48)

In [13]:
df['target'].value_counts()

target
0    896
1     41
Name: count, dtype: int64

#### Selecting the Dependent and Independent from the Test datasets

In [14]:
x=test.drop('target',axis=1)
y=test['target']
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(937, 47)
(937,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


#### Splitting thte Training and Testing datas from the Test dataset

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(655, 47)
(282, 47)
(655,)
(282,)


#### Evaluating the Model

In [16]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [17]:
def cls_eval(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print(cm)
    print('Accuracy Score', accuracy_score(ytest,ypred))
    print(classification_report(ytest,ypred))
    
def mscore(model):
    print('Training Score',model.score(x_train,y_train)) 
    print('Testing Score',model.score(x_test,y_test)) 

#### Building a model with BAGGING CLASSIFIER ENSEMBLE

#### Building and Evaluating bagging model with using LOGISTIC REGRESSION

In [18]:
from sklearn.linear_model import LogisticRegression

In [70]:
lr = LogisticRegression(C=0.1,max_iter=100,random_state=45)
lr.fit(x_train, y_train)

LogisticRegression(C=0.1, random_state=45)

In [71]:
mscore(lr)

Training Score 0.9526717557251908
Testing Score 0.950354609929078


In [72]:
ypred_lr = lr.predict(x_test)
ypred_lr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [73]:
cls_eval(y_test,ypred_lr)

[[265   6]
 [  8   3]]
Accuracy Score 0.950354609929078
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       271
           1       0.33      0.27      0.30        11

    accuracy                           0.95       282
   macro avg       0.65      0.63      0.64       282
weighted avg       0.95      0.95      0.95       282



In [74]:
lr_accuracy_score = accuracy_score(y_test, ypred_lr)
print('LogisticRegression_accuracy score:',lr_accuracy_score)

LogisticRegression_accuracy score: 0.950354609929078


####  Building and Evaluating bagging model with using RANDOM FOREST CLASSIFIER

In [76]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
rfc = RandomForestClassifier( n_estimators=100,max_depth=5,min_samples_split=5, max_features='sqrt', random_state=42,criterion='gini')

rfc.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, min_samples_split=5, random_state=42)

In [78]:
mscore(rfc)

Training Score 0.9755725190839695
Testing Score 0.9645390070921985


In [79]:
ypred_rfc = rfc.predict(x_test)
ypred_rfc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [80]:
cls_eval(y_test,ypred_rfc)

[[271   0]
 [ 10   1]]
Accuracy Score 0.9645390070921985
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       271
           1       1.00      0.09      0.17        11

    accuracy                           0.96       282
   macro avg       0.98      0.55      0.57       282
weighted avg       0.97      0.96      0.95       282



In [81]:
rfc_accuracy_score = accuracy_score(y_test, ypred_rfc)
print('RandomForest_accuracy score:',rfc_accuracy_score)

RandomForest_accuracy score: 0.9645390070921985


#### Building and Evaluating the Bagging model with DECISION TREE CLASSIFIER


In [83]:
from sklearn.tree import DecisionTreeClassifier

In [84]:
dtc = DecisionTreeClassifier(max_depth=5,min_samples_leaf=5,min_samples_split=10,random_state=42,criterion='gini')

dtc.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [85]:
mscore(dtc)

Training Score 0.9801526717557252
Testing Score 0.9609929078014184


In [86]:
ypred_dtc = dtc.predict(x_test)
ypred_dtc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [87]:
cls_eval(y_test,ypred_dtc)


[[268   3]
 [  8   3]]
Accuracy Score 0.9609929078014184
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       271
           1       0.50      0.27      0.35        11

    accuracy                           0.96       282
   macro avg       0.74      0.63      0.67       282
weighted avg       0.95      0.96      0.96       282



In [88]:
accuracy_score_dtc = accuracy_score(y_test, ypred_dtc)
print("Accuracy Score:",  accuracy_score_dtc)

Accuracy Score: 0.9609929078014184


#### Choosing the Best Model

In [89]:
acc_log = accuracy_score(y_test,ypred_lr)
acc_randf = accuracy_score(y_test,ypred_rfc)
acc_dec = accuracy_score(y_test,ypred_dtc)

print('Accuracy of LogisticRegression Model is',acc_log)
print('Accuracy of Random Forest Classifier Model is',acc_randf)
print('Accuracy of Decision Tree Classifier Model is',acc_dec)


Accuracy of LogisticRegression Model is 0.950354609929078
Accuracy of Random Forest Classifier Model is 0.9645390070921985
Accuracy of Decision Tree Classifier Model is 0.9609929078014184


##### Random forest classifier has the highest accuracy score. so i chosen that Random forest classifier as a Best Model 

In [90]:
test.columns

Index(['f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10', 'f_11',
       'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19', 'f_20',
       'f_21', 'f_22', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28', 'f_29', 'f_30',
       'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37', 'f_38', 'f_39',
       'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46', 'f_47', 'f_48',
       'f_49', 'target'],
      dtype='object')

In [91]:
x_train.columns

Index(['f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10', 'f_11',
       'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19', 'f_20',
       'f_21', 'f_22', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28', 'f_29', 'f_30',
       'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37', 'f_38', 'f_39',
       'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46', 'f_47', 'f_48',
       'f_49'],
      dtype='object')

In [92]:
test_pred =rfc.predict(x)

#### Predicted values of Test dataset

In [93]:
test['count_pred']=test_pred
test.head(30)

f_2      f_3      f_4  f_5       f_6    f_7    f_8      f_9  f_10   
0    2558  1506.09   456.63   90   6395000  40.88   7.89  29780.0  0.19  \
1   22325    79.11   841.03  180  55812500  51.11   1.21  61900.0  0.02   
2     115  1449.85   608.43   88    287500  40.42   7.34   3340.0  0.18   
3    1201  1562.53   295.65   66   3002500  42.40   7.97  18030.0  0.19   
4     312   950.27   440.86   37    780000  41.43   7.03   3350.0  0.17   
5      54  1438.13   544.91   82    135000  44.67   6.92   1570.0  0.15   
6     116  1446.29   580.94   97    290000  41.53   6.24   3660.0  0.15   
7      57    28.68   715.39  141    142500  51.67   0.83   1810.0  0.02   
8     188   964.23   456.23   22    470000  38.90   5.89   3720.0  0.15   
9      64   903.02   274.88   33    160000  41.22   7.90   1850.0  0.19   
10     59  1127.41  1507.76   42    147500  47.59   4.72   1800.0  0.10   
11    329  1627.54  1409.43   51    822500  35.00   6.10   4610.0  0.17   
12   3234  1091.56  1357.96   32   8085000  40.08   8.98  25450.0  0.22   
13   2339  1537.68  1633.02   45   5847500  38.13   9.29  22110.0  0.24   
14   2971  1020.91   630.80   59   7427500  32.76  10.48  17380.0  0.32   
15   3155  1118.08   469.39   11   7887500  30.41   7.99  15880.0  0.26   
16  11475  1249.47  1386.03   41  28687500  38.57   9.50  58790.0  0.25   
17   1034  1776.55  1464.70   52   2585000  39.30  14.51  12990.0  0.37   
18   1035  1304.90  1281.72   68   2587500  35.90   7.51  15420.0  0.21   
19   4851  1700.15  1345.04   52  12127500  34.47   7.60  49430.0  0.22   
20   2899  1533.91  1713.00   45   7247500  41.88  11.07  21180.0  0.26   
21   1655  1761.30  1430.22   90   4137500  35.38   9.05  21570.0  0.26   
22   2664  1344.49  1363.74   45   6660000  38.72   8.75  28160.0  0.23   
23    936  1095.47  1416.49   54   2340000  41.06   8.16  10920.0  0.20   
24    486  1628.99  1627.11   39   1215000  36.71   9.49   7820.0  0.26   
25    851  1422.20  1749.68   34   2127500  33.83   8.27   9520.0  0.24   
26   1396  1608.04  1545.25   54   3490000  34.37   8.36  18590.0  0.24   
27   2503  1501.49  1141.62   90   6257500  33.76   9.43  29030.0  0.28   
28     65  1579.09   995.74   43    162500  38.34   5.89   2350.0  0.15   
29    191  1732.70  1238.70   36    477500  39.80   6.71   5050.0  0.17   

     f_11  ...      f_42     f_43     f_44   f_45  f_46      f_47   f_48   
0   214.7  ...   1000.00   763.16   135.46   3.73     0  33243.19  65.74  \
1   901.7  ...  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73   
2    86.1  ...    250.00   150.00    45.13   9.33     1  31692.84  65.81   
3   166.5  ...    761.58   453.21   144.97  13.33     1  37696.21  65.67   
4   232.8  ...    710.63   512.54   109.16   2.58     0  29038.17  65.66   
5    86.0  ...    200.00   150.00    52.22   4.06     0  30967.25  65.77   
6    79.2  ...    403.11   164.58   114.82   6.44     0  31258.37  65.79   
7    78.7  ...    360.56   165.71   132.47   3.02     0  51985.06  65.67   
8   126.3  ...    492.44   256.77   124.72   6.11     0  28871.82  65.67   
9    86.5  ...    223.61   182.83    50.12   2.58     0  32053.95  65.58   
10   81.9  ...    212.13   120.21    47.73   5.88     0  55128.46  66.18   
11  178.4  ...    710.63   451.78   150.85   3.23     0   4530.75  66.25   
12  317.7  ...   3095.56  1937.42   773.69   2.21     0   4927.51  66.15   
13  264.5  ...   2404.16  1530.38   659.67   2.59     0   4732.04  66.34   
14  427.4  ...   1749.29  1245.07   348.70   4.54     0  25579.34  65.78   
15  496.7  ...   3059.41  2043.90   477.23   1.70     0  28172.07  65.72   
16  488.0  ...   4816.64  3894.10   593.54   1.63     0   5514.48  66.18   
17  199.0  ...   1140.18   651.51   300.07   5.80     0   4535.86  66.29   
18  167.8  ...   1234.91   632.82   358.06   6.98     0   6165.56  66.14   
19  245.3  ...   2600.48  1983.69   387.60   1.60     0   4236.17  66.23   
20  342.2  ...   2050.61  1506.78   307.58   2.58     0   4084.14  66.38   
21  191.

#### Loading predicted values of a test dataset into csv file

In [94]:
test.to_csv('oilspill_prediction.csv')

#### Applying the best model in the original dataset

In [95]:
original_data=pd.read_csv(r'G:\My Drive\oil_spill.csv')
original_data

f_1    f_2      f_3     f_4  f_5       f_6    f_7    f_8      f_9  f_10   
0      1   2558  1506.09  456.63   90   6395000  40.88   7.89  29780.0  0.19  \
1      2  22325    79.11  841.03  180  55812500  51.11   1.21  61900.0  0.02   
2      3    115  1449.85  608.43   88    287500  40.42   7.34   3340.0  0.18   
3      4   1201  1562.53  295.65   66   3002500  42.40   7.97  18030.0  0.19   
4      5    312   950.27  440.86   37    780000  41.43   7.03   3350.0  0.17   
..   ...    ...      ...     ...  ...       ...    ...    ...      ...   ...   
932  200     12    92.42  364.42  135     97200  59.42  10.34    884.0  0.17   
933  201     11    98.82  248.64  159     89100  59.64  10.18    831.0  0.17   
934  202     14    25.14  428.86   24    113400  60.14  17.94    847.0  0.30   
935  203     10    96.00  451.30   68     81000  59.90  15.01    831.0  0.25   
936  204     11     7.73  235.73  135     89100  61.82  12.24    831.0  0.20   

     ...     f_41      f_42     f_43     f_44   f_45  f_46      f_47   f_48   
0    ...  2850.00   1000.00   763.16   135.46   3.73     0  33243.19  65.74  \
1    ...  5750.00  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73   
2    ...  1400.00    250.00   150.00    45.13   9.33     1  31692.84  65.81   
3    ...  6041.52    761.58   453.21   144.97  13.33     1  37696.21  65.67   
4    ...  1320.04    710.63   512.54   109.16   2.58     0  29038.17  65.66   
..   ...      ...       ...      ...      ...    ...   ...       ...    ...   
932  ...   381.84    254.56    84.85   146.97   4.50     0   2593.50  65.85   
933  ...   284.60    180.00   150.00    51.96   1.90     0   4361.25  65.70   
934  ...   402.49    180.00   180.00     0.00   2.24     0   2153.05  65.91   
935  ...   402.49    180.00    90.00    73.48   4.47     0   2421.43  65.97   
936  ...   254.56    254.56   127.28   180.00   2.00     0   3782.68  65.65   

     f_49  target  
0    7.95       1  
1    6.26       0  
2    7.84       1  
3    8.07       1  
4    7.35       0  
..    ...     ...  
932  6.39       0  
933  6.53       0  
934  6.12       0  
935  6.32       0  
936  6.26       0  

[937 rows x 50 columns]

In [96]:
i=original_data.drop('target',axis=1)
j=original_data['target']
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(937, 47)
(937,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [97]:
from sklearn.model_selection import train_test_split
i_train,i_test,j_train,j_test=train_test_split(i,j,test_size=0.30,random_state=42)
print(i_train.shape)
print(i_test.shape)
print(j_train.shape)
print(j_test.shape)

(655, 49)
(282, 49)
(655,)
(282,)


In [98]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [99]:
def cls_eval(jtest,jpred):
    cm = confusion_matrix(jtest,jpred)
    print(cm)
    print('Accuracy Score', accuracy_score(jtest,jpred))
    print(classification_report(jtest,jpred))
    
def mscore(model):
    print('Training Score',model.score(i_train,j_train)) 
    print('Testing Score',model.score(i_test,j_test)) 

In [100]:
rand_forest = RandomForestClassifier( n_estimators=100,max_depth=5,min_samples_split=5, max_features='sqrt', random_state=42,criterion='gini')

rand_forest.fit(i_train, j_train)

RandomForestClassifier(max_depth=5, min_samples_split=5, random_state=42)

In [101]:
mscore(rand_forest)

Training Score 0.9755725190839695
Testing Score 0.9680851063829787


In [102]:
jpred_rand_forest = rand_forest.predict(i_test)
jpred_rand_forest

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [103]:
cls_eval(j_test,jpred_rand_forest)

[[270   1]
 [  8   3]]
Accuracy Score 0.9680851063829787
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       271
           1       0.75      0.27      0.40        11

    accuracy                           0.97       282
   macro avg       0.86      0.63      0.69       282
weighted avg       0.96      0.97      0.96       282



In [104]:
rand_forest_accuracy_score = accuracy_score(j_test, jpred_rand_forest)
print('RandomForest_accuracy score for original dataset:',rand_forest_accuracy_score)

RandomForest_accuracy score for original dataset: 0.9680851063829787


In [105]:
original_data.columns

Index(['f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10',
       'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19',
       'f_20', 'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28',
       'f_29', 'f_30', 'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37',
       'f_38', 'f_39', 'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46',
       'f_47', 'f_48', 'f_49', 'target'],
      dtype='object')

In [106]:
i_train.columns

Index(['f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10',
       'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19',
       'f_20', 'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28',
       'f_29', 'f_30', 'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37',
       'f_38', 'f_39', 'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46',
       'f_47', 'f_48', 'f_49'],
      dtype='object')

In [107]:
original_data_pred =rand_forest.predict(i)

#### Original Datasets Prediction values

In [108]:
original_data['prediction_value']=original_data_pred
original_data.head(20)

f_1    f_2      f_3      f_4  f_5       f_6    f_7    f_8      f_9  f_10   
0     1   2558  1506.09   456.63   90   6395000  40.88   7.89  29780.0  0.19  \
1     2  22325    79.11   841.03  180  55812500  51.11   1.21  61900.0  0.02   
2     3    115  1449.85   608.43   88    287500  40.42   7.34   3340.0  0.18   
3     4   1201  1562.53   295.65   66   3002500  42.40   7.97  18030.0  0.19   
4     5    312   950.27   440.86   37    780000  41.43   7.03   3350.0  0.17   
5     6     54  1438.13   544.91   82    135000  44.67   6.92   1570.0  0.15   
6     7    116  1446.29   580.94   97    290000  41.53   6.24   3660.0  0.15   
7     8     57    28.68   715.39  141    142500  51.67   0.83   1810.0  0.02   
8     9    188   964.23   456.23   22    470000  38.90   5.89   3720.0  0.15   
9    10     64   903.02   274.88   33    160000  41.22   7.90   1850.0  0.19   
10   11     59  1127.41  1507.76   42    147500  47.59   4.72   1800.0  0.10   
11    1    329  1627.54  1409.43   51    822500  35.00   6.10   4610.0  0.17   
12    2   3234  1091.56  1357.96   32   8085000  40.08   8.98  25450.0  0.22   
13    3   2339  1537.68  1633.02   45   5847500  38.13   9.29  22110.0  0.24   
14    4   2971  1020.91   630.80   59   7427500  32.76  10.48  17380.0  0.32   
15    5   3155  1118.08   469.39   11   7887500  30.41   7.99  15880.0  0.26   
16    6  11475  1249.47  1386.03   41  28687500  38.57   9.50  58790.0  0.25   
17    7   1034  1776.55  1464.70   52   2585000  39.30  14.51  12990.0  0.37   
18    8   1035  1304.90  1281.72   68   2587500  35.90   7.51  15420.0  0.21   
19    9   4851  1700.15  1345.04   52  12127500  34.47   7.60  49430.0  0.22   

    ...      f_42     f_43     f_44   f_45  f_46      f_47   f_48  f_49   
0   ...   1000.00   763.16   135.46   3.73     0  33243.19  65.74  7.95  \
1   ...  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73  6.26   
2   ...    250.00   150.00    45.13   9.33     1  31692.84  65.81  7.84   
3   ...    761.58   453.21   144.97  13.33     1  37696.21  65.67  8.07   
4   ...    710.63   512.54   109.16   2.58     0  29038.17  65.66  7.35   
5   ...    200.00   150.00    52.22   4.06     0  30967.25  65.77  7.85   
6   ...    403.11   164.58   114.82   6.44     0  31258.37  65.79  7.85   
7   ...    360.56   165.71   132.47   3.02     0  51985.06  65.67  6.25   
8   ...    492.44   256.77   124.72   6.11     0  28871.82  65.67  7.36   
9   ...    223.61   182.83    50.12   2.58     0  32053.95  65.58  7.35   
10  ...    212.13   120.21    47.73   5.88     0  55128.46  66.18  7.18   
11  ...    710.63   451.78   150.85   3.23     0   4530.75  66.25  7.85   
12  ...   3095.56  1937.42   773.69   2.21     0   4927.51  66.15  7.24   
13  ...   2404.16  1530.38   659.67   2.59     0   4732.04  66.34  7.67   
14  ...   1749.29  1245.07   348.70   4.54     0  25579.34  65.78  7.41   
15  ...   3059.41  2043.90   477.23   1.70     0  28172.07  65.72  7.58   
16  ...   4816.64  3894.10   593.54   1.63     0   5514.48  66.18  7.41   
17  ...   1140.18   651.51   300.07   5.80     0   4535.86  66.29  8.01   
18  ...   1234.91   632.82   358.06   6.98     0   6165.56  66.14  7.52   
19  ...   2600.48  1983.69   387.60   1.60     0   4236.17  66.23  7.96   

    target  prediction_value  
0        1                 1  
1        0                 0  
2        1                 1  
3        1                 1  
4        0                 1  
5        1                 1  
6        1                 1  
7        0                 0  
8        1                 1  
9        1                 1  
10       1                 0  
11       0                 0  
12       0                 0  
13       0                 0  
14       1                 1  
15       1                 1  
16       0                 0  
17       0                 0  
18       0                 0  
19       0                 0  

[20 rows x 51 columns]